services:
  backend:
    build:
      context: ./backend
    container_name: us-data-demo-backend
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    container_name: us-data-demo-frontend
    ports:
      - "3000:80"
