# Use the official Nginx image based on Alpine Linux.
# Alpine is a lightweight Linux distribution.
FROM nginx:alpine

# Copy the Nginx configuration file (default.conf) to the appropriate
# directory in the (Ngix) container.
COPY default.conf /etc/nginx/conf.d/
